services:
  public:
    host: localhost
    port: 8110
    root: /oauth2

jwt:
  refreshtokens:
    secret: refresh_testsecret
    algorithm: HS256
    lifetime: ${JWT_LIFETIME:-43200}  # 12 x 3600
  accesstokens:
    secret: access_testsecret
    algorithm: HS256
    lifetime: 300

postgres:
  host: ${DB_HOST:-localhost}
  port: ${DB_PORT:-5432}
  user: ${DB_USER:-oauthuser}
  password: ${DB_PASS:-oauthpassword}
  dbname: ${DB_DATABASE:-oauth}

logging:
  version: 1
  formatters:
    root:
      format: "%(asctime)s	%(name)s %(levelname)s (%(pathname)s/%(filename)s:%(funcName)s@%(lineno)d): %(message)s"
    auditlog:
      format: "%(asctime)s	%(name)s %(levelname)s (pid: %(process)d | ts: %(created)f) %(message)s"
    werkzeug:
      format: "%(asctime)s	%(name)s %(levelname)s: %(message)s"
  handlers:
    root:
      class : logging.StreamHandler
      formatter: root
    auditlog:
      class : logging.StreamHandler
      formatter: auditlog
    werkzeug:
      class : logging.StreamHandler
      formatter: werkzeug
  loggers:
    auditlog.authserver:
      level: DEBUG
      propagate: false
      handlers: [auditlog]
    werkzeug:
      propagate: false
      handlers: [werkzeug]
  root:
    level: ${LOGLEVEL:-DEBUG}
    handlers: [root]
