version: '3'

services:

  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=authz_admin
      - POSTGRES_USER=authz_admin
      - POSTGRES_PASSWORD=authz_admin

  authz_admin:
    build: .
    links:
      - database:database
    ports:
      - "8120:8000"
    environment:
      JWT_ACCESS_SECRET: accesssecret
      DB_HOST: database
      AUTHZ_ADMIN_API_KEY: apikey
      DATAPUNT_ENVIRONMENT: development
