version: '3'

services:

  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=authz_admin
      - POSTGRES_USER=authz_admin
      - POSTGRES_PASSWORD=authz_admin

  authz_admin:
    build: .
    links:
      - database:database
    ports:
      - "8120:8000"
    environment:
      PUB_JWKS: >
        {
        "keys": [
            {
              "kty": "EC",
              "key_ops": [
                "verify",
                "sign"
              ],
              "kid": "2aedafba-8170-4064-b704-ce92b7c89cc6",
              "crv": "P-256",
              "x": "6r8PYwqfZbq_QzoMA4tzJJsYUIIXdeyPA27qTgEJCDw=",
              "y": "Cf2clfAfFuuCB06NMfIat9ultkMyrMQO9Hd2H7O9ZVE=",
              "d": "N1vu0UQUp0vLfaNeM0EDbl4quvvL6m_ltjoAXXzkI3U="
          }
        ]
        }
      DB_HOST: database
      AUTHZ_ADMIN_API_KEY: apikey
      DATAPUNT_ENVIRONMENT: development
